# Generated by Django 4.2.6 on 2023-10-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_category2_category_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category2',
        ),
    ]
